### ISSUE TITLE
Restore up, down, & top5% view on outlier analysis list page

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook_#19]
Up, down, and top5% gene summaries were removed from the outlier analysis list page for performance reasons.

I've been informed that these were useful, so let's restore them. 
suggested: add a summary count for each of these to all outlier analysis jobs, that is populated when the job is completed.

Also add a migration to populate these counts for existing jobs.

**Comment by mokolodi1** [comment]
#36 adds all of this.

**Comment by mokolodi1** [comment]
Live on prod!
