### ISSUE TITLE
collaborations - not all collabs appear as options when scrolling [07/27/2016]

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook_#21]
(not yet reproduced) Some collaborations are not visible in the 'share with this collaboration' list, but appear when you begin to type them in.

From an email thread back in July:

"I can't see Linh's address in the list that comes up when I click "share"."
"it did not appear on the list when you scrolled, but when you started to type it, it appeared as an option? is that what happened?"
"Yes, exactly."

**Comment by mokolodi1** [comment]
I believe this is because sometimes you have to scroll _up_ to find some emails. I've experienced before and I don't know what causes it or how to fix it other than to revamp the UI.

**Comment by mokolodi1** [comment]
Didn't mean to close it!

**Comment by mokolodi1** [comment]
New sharing modal makes this issue obsolete.
