### ISSUE TITLE
Issues found on teo.medbook.io

### ISSUE THREAD

**Issue by cygao** [UCSC-MedBook/MedBook_#37]
- /Share/Edit collaborators: ‘search for people or collaboraitons’ spelling
- Edit collaborators: Can add the same collaborator twice

- GSEA/run a new:Advanced arguments rollover link [http://software.broadinstitute.org/cancer/software/gsea/doc/GSEAUserGuideFrame.html] 404s

- Limma, Single Sample Top Genes/Result: Run GSEA button doesn’t work

**Comment by mokolodi1** [comment]
> Limma, Single Sample Top Genes/Result: Run GSEA button doesn’t work

This is because I ran the migration script after these jobs had already been run, destroying the gene sets that were linked to the jobs @cygao was looking at.
