### ISSUE TITLE
Add Mocha test runner

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook_#4]
see https://guide.meteor.com/testing.html
- [ ] add to jobRunner
- [ ] add to wrangler
- [ ] set up a script to spin up docker container in test mode

**Comment by e-t-k** [comment]
`meteor test` requires 1.3+. Both jobrunner and wrangler are on 1.1.0.3. Let's migrate this jobrunner to Meteor 1.4 and see what breaks!

**Comment by mokolodi1** [comment]
Done! We have a long way to go with adding tests, but the Mocha test runner has been added and is running in CI.
