### ISSUE TITLE
Document how & when to apply migrations

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook_#42]
pull #36 requires a migration . 
We should have a document dev-ops/migrations/README.md that describes the step by step process of applying a migration as part of a deploy, including a back-out plan. I imagine it's something like this?

* test with dev db that have migration already applied
* code review, push to master, build new dockers
* check out master on staging
* apply migration to staging db
* spin up new dockers and test

* stop dockers on prod (except mongo)
* take a backup of the db
* apply migration
* spin up new dockers

and a back-out plan of:
- stop new dockers
- restore db from the fresh backup
- spin up old dockers

**Comment by mokolodi1** [comment]
I've added this list in #64
