### ISSUE TITLE
Ted's GSEA comments

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook_#43]
1. Love the clear easy to find export buttons. But we need to export to tsv file from the main  Handsontable widget too.  Perhaps https://docs.handsontable.com/pro/1.0.0-beta3/demo-export-file.html

2. I really need to sort by column. Something like
```
var hot = new Handsontable(..., {
  // ...
  columnSorting: true
});
```

**Comment by mokolodi1** [comment]
@tedgoldstein: Handsontable only supports `csv` as a file type and not `tsv`. Is that okay, or do you prefer `tsv`?

**Comment by mokolodi1** [comment]
See `hot-updates` brach...

**Comment by tedgoldstein** [comment]
TSV is ok.
Ted

**Comment by mokolodi1** [comment]
Do you mean CSV is okay or I should go make TSV work?

**Comment by tedgoldstein** [comment]
CSV is okay.  Keep it simple.
Thanks
Ted

**Comment by mokolodi1** [comment]
See #46.
