### ISSUE TITLE
experimentally update job runner meteor version to 1.3

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook_#5]
Need Meteor 1.3 + for `meteor test`

Breaking changes list - nothing looks relevant
1.1 -> 1.2 : https://github.com/meteor/docs/blob/version-NEXT/long-form/breaking-changes-1.2.md
1.3 : https://guide.meteor.com/1.3-migration.html

Tried updating to 1.4, but after doing so, got the following:

`{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
 (STDERR) js-bson: Failed to load c++ bson extension, using pure JS version`

Seems to be [traced to CFS:gridfs](https://github.com/meteor/meteor/issues/7477#issuecomment-235695897) & doesn't appear in 1.3

So let's hold off on 1.4 until after we get rid of CFS; it seems that 1.3 to 1.4 is mostly similar anyhow.

**Comment by mokolodi1** [comment]
@e-t-k did a fab job and job-runner is now on Meteor 1.3.
