### ISSUE TITLE
be aware: might the shared /packages dir become a problem

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook_#9]
Right now, all apps get the packages/ dir included when they're built in docker.

This means (especially as I add patient care) that jobrunner will have access to, eg, the jquery-querybuilder package when it didn't before.

Keep an eye out for potential effects of this.

**Comment by mokolodi1** [comment]
This shouldn't be a problem because the apps only load the packages that
are listed in the .meteor/packages file. Still good to be aware of though!

**Comment by mokolodi1** [comment]
Given we've successfully transitioned to MedBook_ on production and this hasn't presented any issues as of yet, I'm going to go ahead and close this. Feel free to reopen, @e-t-k.
